#ifndef __BSP_TEMP_PRES_DRV_H
#define	__BSP_TEMP_PRES_DRV_H

#include "stm32f4xx.h"

#ifdef __cplusplus
#if __cplusplus
extern "C"{
#endif
#endif


#define RHEOSTAT_NOFCHANEL      18

//AI1
#define RHEOSTAT_ADC_GPIO_PORT1             GPIOF
#define RHEOSTAT_ADC_GPIO_PIN1              GPIO_PIN_3
#define RHEOSTAT_ADC_GPIO_CLK1_ENABLE()     __GPIOF_CLK_ENABLE()
#define RHEOSTAT_ADC_CHANNEL1               ADC_CHANNEL_9


//AI2
#define RHEOSTAT_ADC_GPIO_PORT2             GPIOF
#define RHEOSTAT_ADC_GPIO_PIN2              GPIO_PIN_4
#define RHEOSTAT_ADC_GPIO_CLK2_ENABLE()     __GPIOF_CLK_ENABLE()
#define RHEOSTAT_ADC_CHANNEL2               ADC_CHANNEL_14

//AI3
#define RHEOSTAT_ADC_GPIO_PORT3				GPIOF
#define RHEOSTAT_ADC_GPIO_PIN3				GPIO_PIN_5
#define RHEOSTAT_ADC_GPIO_CLK3_ENABLE()		__GPIOF_CLK_ENABLE()
#define RHEOSTAT_ADC_CHANNEL3				ADC_CHANNEL_15

//AI4
#define RHEOSTAT_ADC_GPIO_PORT4             GPIOF
#define RHEOSTAT_ADC_GPIO_PIN4              GPIO_PIN_6
#define RHEOSTAT_ADC_GPIO_CLK4_ENABLE()     __GPIOF_CLK_ENABLE()
#define RHEOSTAT_ADC_CHANNEL4               ADC_CHANNEL_4

//AI5
#define RHEOSTAT_ADC_GPIO_PORT5             GPIOF
#define RHEOSTAT_ADC_GPIO_PIN5              GPIO_PIN_7
#define RHEOSTAT_ADC_GPIO_CLK5_ENABLE()     __GPIOF_CLK_ENABLE()
#define RHEOSTAT_ADC_CHANNEL5               ADC_CHANNEL_5

//AI6
#define RHEOSTAT_ADC_GPIO_PORT6             GPIOF
#define RHEOSTAT_ADC_GPIO_PIN6              GPIO_PIN_8
#define RHEOSTAT_ADC_GPIO_CLK6_ENABLE()     __GPIOF_CLK_ENABLE()
#define RHEOSTAT_ADC_CHANNEL6               ADC_CHANNEL_6

//RI1
#define RHEOSTAT_ADC_GPIO_PORT7             GPIOF
#define RHEOSTAT_ADC_GPIO_PIN7              GPIO_PIN_9
#define RHEOSTAT_ADC_GPIO_CLK7_ENABLE()     __GPIOF_CLK_ENABLE()
#define RHEOSTAT_ADC_CHANNEL7               ADC_CHANNEL_7

//RI2
#define RHEOSTAT_ADC_GPIO_PORT8				GPIOF
#define RHEOSTAT_ADC_GPIO_PIN8				GPIO_PIN_10
#define RHEOSTAT_ADC_GPIO_CLK8_ENABLE()		__GPIOF_CLK_ENABLE()
#define RHEOSTAT_ADC_CHANNEL8				ADC_CHANNEL_8

//RI3
#define RHEOSTAT_ADC_GPIO_PORT9				GPIOC
#define RHEOSTAT_ADC_GPIO_PIN9				GPIO_PIN_0
#define RHEOSTAT_ADC_GPIO_CLK9_ENABLE()		__GPIOC_CLK_ENABLE()
#define RHEOSTAT_ADC_CHANNEL9				ADC_CHANNEL_10

//BATS
#define _RHEOSTAT_ADC_GPIO_PORT1			GPIOC
#define _RHEOSTAT_ADC_GPIO_PIN1				GPIO_PIN_1
#define _RHEOSTAT_ADC_GPIO_CLK1_ENABLE()	__GPIOC_CLK_ENABLE()
#define _RHEOSTAT_ADC_CHANNEL1				ADC_CHANNEL_11

//5V_Detector
#define _RHEOSTAT_ADC_GPIO_PORT2			GPIOC
#define _RHEOSTAT_ADC_GPIO_PIN2				GPIO_PIN_4
#define _RHEOSTAT_ADC_GPIO_CLK2_ENABLE()	__GPIOC_CLK_ENABLE()
#define _RHEOSTAT_ADC_CHANNEL2				ADC_CHANNEL_14

//3V3_Detector
#define _RHEOSTAT_ADC_GPIO_PORT3			GPIOC
#define _RHEOSTAT_ADC_GPIO_PIN3				GPIO_PIN_5
#define _RHEOSTAT_ADC_GPIO_CLK3_ENABLE()	__GPIOC_CLK_ENABLE()
#define _RHEOSTAT_ADC_CHANNEL3				ADC_CHANNEL_15

//DO_IN1
#define _RHEOSTAT_ADC_GPIO_PORT4			GPIOA
#define _RHEOSTAT_ADC_GPIO_PIN4				GPIO_PIN_2
#define _RHEOSTAT_ADC_GPIO_CLK4_ENABLE()	__GPIOA_CLK_ENABLE()
#define _RHEOSTAT_ADC_CHANNEL4				ADC_CHANNEL_2

//DO_IN2
#define _RHEOSTAT_ADC_GPIO_PORT5			GPIOA
#define _RHEOSTAT_ADC_GPIO_PIN5				GPIO_PIN_3
#define _RHEOSTAT_ADC_GPIO_CLK5_ENABLE()	__GPIOA_CLK_ENABLE()
#define _RHEOSTAT_ADC_CHANNEL5				ADC_CHANNEL_3

//DO_IN3
#define _RHEOSTAT_ADC_GPIO_PORT6			GPIOA
#define _RHEOSTAT_ADC_GPIO_PIN6				GPIO_PIN_5
#define _RHEOSTAT_ADC_GPIO_CLK6_ENABLE()	__GPIOA_CLK_ENABLE()
#define _RHEOSTAT_ADC_CHANNEL6				ADC_CHANNEL_5

//DO_IN4
#define _RHEOSTAT_ADC_GPIO_PORT7			GPIOA
#define _RHEOSTAT_ADC_GPIO_PIN7				GPIO_PIN_7
#define _RHEOSTAT_ADC_GPIO_CLK7_ENABLE()	__GPIOA_CLK_ENABLE()
#define _RHEOSTAT_ADC_CHANNEL7				ADC_CHANNEL_7

//DO_IN5
#define _RHEOSTAT_ADC_GPIO_PORT8			GPIOB
#define _RHEOSTAT_ADC_GPIO_PIN8				GPIO_PIN_0
#define _RHEOSTAT_ADC_GPIO_CLK8_ENABLE()	__GPIOB_CLK_ENABLE()
#define _RHEOSTAT_ADC_CHANNEL8				ADC_CHANNEL_8

//DO_IN6
#define _RHEOSTAT_ADC_GPIO_PORT9			GPIOB
#define _RHEOSTAT_ADC_GPIO_PIN9				GPIO_PIN_1
#define _RHEOSTAT_ADC_GPIO_CLK9_ENABLE()	__GPIOB_CLK_ENABLE()
#define _RHEOSTAT_ADC_CHANNEL9				ADC_CHANNEL_9




#define RHEOSTAT_ADC                        ADC3
#define RHEOSTAT_ADC_CLK_ENABLE()           __ADC3_CLK_ENABLE()

#define _RHEOSTAT_ADC						ADC1
#define _RHEOSTAT_ADC_CLK_ENABLE()			__ADC1_CLK_ENABLE()

#define RHEOSTAT_ADC_DR_ADDR                ((uint32_t)ADC3+0x4c)
#define _RHEOSTAT_ADC_DR_ADDR				((uint32_t)ADC1+0x4c)


#define RHEOSTAT_ADC_DMA_CLK_ENABLE()       __DMA2_CLK_ENABLE()
#define RHEOSTAT_ADC_DMA_CHANNEL            DMA_CHANNEL_0
#define RHEOSTAT_ADC_DMA_STREAM             DMA2_Stream0

extern void Error_Handler(void);

void Rheostat_Init(void);

extern void Rheostat_Init(void);

#ifdef __cplusplus
#if __cplusplus
}
#endif
#endif

#endif






